CREATE TABLE admin_centers_ru (
    id  serial primary key,
    region varchar(30),
    centre varchar(30)
);

INSERT INTO admin_centers_ru(region, centre) values('Амурская', ' Благовещенск');
INSERT INTO admin_centers_ru(region, centre) values('Архангельская', ' Архангельск');
INSERT INTO admin_centers_ru(region, centre) values('Астраханская', ' Астрахань');
INSERT INTO admin_centers_ru(region, centre) values('Белгородская', ' Белгород');
INSERT INTO admin_centers_ru(region, centre) values('Брянская', ' Брянск');
INSERT INTO admin_centers_ru(region, centre) values('Владимирская', ' Владимир');
INSERT INTO admin_centers_ru(region, centre) values('Волгоградская', ' Волгоград');
INSERT INTO admin_centers_ru(region, centre) values('Вологодская', ' Вологда');
INSERT INTO admin_centers_ru(region, centre) values('Воронежская', ' Воронеж');
INSERT INTO admin_centers_ru(region, centre) values('Ивановская', ' Иваново');
INSERT INTO admin_centers_ru(region, centre) values('Иркутская', ' Иркутск');
INSERT INTO admin_centers_ru(region, centre) values('Калининградская', ' Калининград');
INSERT INTO admin_centers_ru(region, centre) values('Калужская', ' Калуга');
INSERT INTO admin_centers_ru(region, centre) values('Кемеровская', ' Кемерово');
INSERT INTO admin_centers_ru(region, centre) values('Кировская', ' Киров');
INSERT INTO admin_centers_ru(region, centre) values('Костромская', ' Кострома');
INSERT INTO admin_centers_ru(region, centre) values('Курганская', ' Курган');
INSERT INTO admin_centers_ru(region, centre) values('Курская', ' Курск');
INSERT INTO admin_centers_ru(region, centre) values('Ленинградская', ' Санкт-Петербург');
INSERT INTO admin_centers_ru(region, centre) values('Липецкая', ' Липецк');
INSERT INTO admin_centers_ru(region, centre) values('Магаданская', ' Магадан');
INSERT INTO admin_centers_ru(region, centre) values('Московская', ' Москва');
INSERT INTO admin_centers_ru(region, centre) values('Мурманская', ' Мурманск');
INSERT INTO admin_centers_ru(region, centre) values('Нижегородская', ' Нижний Новгород');
INSERT INTO admin_centers_ru(region, centre) values('Новгородская', ' Новгород');
INSERT INTO admin_centers_ru(region, centre) values('Новосибирская', ' Новосибирск');
INSERT INTO admin_centers_ru(region, centre) values('Омская', ' Омск');
INSERT INTO admin_centers_ru(region, centre) values('Оренбургская', ' Оренбург');
INSERT INTO admin_centers_ru(region, centre) values('Орловская', ' Орел');
INSERT INTO admin_centers_ru(region, centre) values('Пензенская', ' Пенза');
INSERT INTO admin_centers_ru(region, centre) values('Псковская', ' Псков');
INSERT INTO admin_centers_ru(region, centre) values('Ростовская', ' Ростов-на-Дону');
INSERT INTO admin_centers_ru(region, centre) values('Рязанская', ' Рязань');
INSERT INTO admin_centers_ru(region, centre) values('Самарская', ' Самара');
INSERT INTO admin_centers_ru(region, centre) values('Саратовская', ' Саратов');
INSERT INTO admin_centers_ru(region, centre) values('Сахалинская', ' Южно-Сахалинск');
INSERT INTO admin_centers_ru(region, centre) values('Свердловская', ' Екатеринбург');
INSERT INTO admin_centers_ru(region, centre) values('Смоленская', ' Смоленск');
INSERT INTO admin_centers_ru(region, centre) values('Тамбовская', ' Тамбов');
INSERT INTO admin_centers_ru(region, centre) values('Тверская', ' Тверь');
INSERT INTO admin_centers_ru(region, centre) values('Томская', ' Томск');
INSERT INTO admin_centers_ru(region, centre) values('Тульская', ' Тула');
INSERT INTO admin_centers_ru(region, centre) values('Тюменская', ' Тюмень');
INSERT INTO admin_centers_ru(region, centre) values('Ульяновская', ' Ульяновск');
INSERT INTO admin_centers_ru(region, centre) values('Челябинская', ' Челябинск');
INSERT INTO admin_centers_ru(region, centre) values('Ярославская', ' Ярославль');
INSERT INTO admin_centers_ru(region, centre) values('Адыгея', ' Майкоп');
INSERT INTO admin_centers_ru(region, centre) values('Алтай', ' Горно-Алтайск');
INSERT INTO admin_centers_ru(region, centre) values('Башкортостан', ' Уфа');
INSERT INTO admin_centers_ru(region, centre) values('Бурятия', ' Улан-Удэ');
INSERT INTO admin_centers_ru(region, centre) values('Дагестан', ' Махачкала');
INSERT INTO admin_centers_ru(region, centre) values('Ингушетия', ' Магас');
INSERT INTO admin_centers_ru(region, centre) values('Кабардино-Балкария', ' Нальчик');
INSERT INTO admin_centers_ru(region, centre) values('Калмыкия', ' Элиста');
INSERT INTO admin_centers_ru(region, centre) values('Карачаево-Черкесская', ' Черкесск');
INSERT INTO admin_centers_ru(region, centre) values('Карелия', ' Петрозаводск');
INSERT INTO admin_centers_ru(region, centre) values('Коми', ' Сыктывкар');
INSERT INTO admin_centers_ru(region, centre) values('Марий Эл', ' Йошкар-Ола');
INSERT INTO admin_centers_ru(region, centre) values('Мордовия', ' Саранск');
INSERT INTO admin_centers_ru(region, centre) values('Саха', ' Якутск');
INSERT INTO admin_centers_ru(region, centre) values('Северная Осетия-Алания', ' Владикавказ');
INSERT INTO admin_centers_ru(region, centre) values('Татарстан', ' Казань');
INSERT INTO admin_centers_ru(region, centre) values('Тыва', ' Кызыл');
INSERT INTO admin_centers_ru(region, centre) values('Удмуртия', ' Ижевск');
INSERT INTO admin_centers_ru(region, centre) values('Хакасия', ' Абакан');
INSERT INTO admin_centers_ru(region, centre) values('Чечня', ' Грозный');
INSERT INTO admin_centers_ru(region, centre) values('Чувашская', ' Чебоксары');
INSERT INTO admin_centers_ru(region, centre) values('Крым', ' Симферополь');
INSERT INTO admin_centers_ru(region, centre) values('Алтайский', ' Барнаул');
INSERT INTO admin_centers_ru(region, centre) values('Забайкальский', ' Чита');
INSERT INTO admin_centers_ru(region, centre) values('Камчатский', ' Петропавловск-Камчатский');
INSERT INTO admin_centers_ru(region, centre) values('Краснодарский', ' Краснодар');
INSERT INTO admin_centers_ru(region, centre) values('Красноярский', ' Красноярск');
INSERT INTO admin_centers_ru(region, centre) values('Пермский', ' Пермь');
INSERT INTO admin_centers_ru(region, centre) values('Приморский', ' Владивосток');
INSERT INTO admin_centers_ru(region, centre) values('Ставропольский', ' Ставрополь');
INSERT INTO admin_centers_ru(region, centre) values('Хабаровский', ' Хабаровск');
INSERT INTO admin_centers_ru(region, centre) values('Ненецкий', ' Нарьян-Мар');
INSERT INTO admin_centers_ru(region, centre) values('Ханты-Мансийский', ' Ханты-Мансийск');
INSERT INTO admin_centers_ru(region, centre) values('Чукотский', ' Анадырь');
INSERT INTO admin_centers_ru(region, centre) values('Ямало-Ненецкий', ' Салехард');
INSERT INTO admin_centers_ru(region, centre) values('Еврейская', ' Биробиджан');